// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function databaseUrl(): string {
  const raw = process.env.DATABASE_URL;
  if (!raw?.trim()) {
    // prisma generate (postinstall) does not connect; migrate deploy needs a real URL at runtime
    return "postgresql://127.0.0.1:5432/placeholder";
  }

  let url = raw.trim().replace(/^["']|["']$/g, "");

  if (url.startsWith("postgres://")) {
    url = "postgresql://" + url.slice("postgres://".length);
  }

  if (!url.startsWith("postgresql://")) {
    const scheme = url.includes(":") ? url.split(":")[0] : "(no scheme)";
    throw new Error(
      `DATABASE_URL must start with postgresql:// or postgres:// (got "${scheme}:"). Use Render's Internal Database URL.`
    );
  }

  if (url.includes("render.com") && !url.includes("sslmode=")) {
    url += url.includes("?") ? "&" : "?";
    url += "sslmode=require";
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl(),
  },
});
