// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function isProductionRuntime(): boolean {
  return (
    process.env.NODE_ENV === "production" ||
    process.env.RENDER === "true" ||
    Boolean(process.env.RENDER_SERVICE_ID)
  );
}

function databaseUrl(): string {
  const raw = process.env.DATABASE_URL;
  if (!raw?.trim()) {
    // prisma generate (postinstall) does not connect; migrate deploy needs a real URL at runtime
    return "postgresql://127.0.0.1:5432/placeholder";
  }

  let url = raw.trim().replace(/^["']|["']$/g, "");

  if (url.startsWith("postgres://")) {
    url = "postgresql://" + url.slice("postgres://".length);
  }

  if (!url.startsWith("postgresql://")) {
    const scheme = url.includes(":") ? url.split(":")[0] : "(no scheme)";
    throw new Error(
      `DATABASE_URL must start with postgresql:// or postgres:// (got "${scheme}:"). Use Render's Internal Database URL.`
    );
  }

  if (!url.includes("sslmode=")) {
    try {
      const parsed = new URL(url);
      if (parsed.hostname.includes("render.com")) {
        parsed.searchParams.set("sslmode", "require");
        return parsed.toString();
      }

      // Internal Render hostname — allowed on Render; blocked locally (use External URL)
      if (
        !isProductionRuntime() &&
        /^dpg-[a-z0-9-]+$/i.test(parsed.hostname)
      ) {
        throw new Error(
          `DATABASE_URL uses Render internal host "${parsed.hostname}". ` +
            "From your laptop use the External Database URL (host ends with .render.com), " +
            "or push to Render and let deploy run migrations."
        );
      }
    } catch (err) {
      if (err instanceof Error && err.message.includes("Render internal")) throw err;
      // keep url as-is
    }
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl(),
  },
});
