databases:
  - name: todo-db
    plan: free
    databaseName: todo
    user: todo

services:
  - type: web
    name: todo-app
    runtime: node
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build
    preDeployCommand: npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
